/* Catálogo aportado por el usuario. Los movimientos ambiguos no se asignan automáticamente. */
(function () {
  'use strict';
  const rows = [
    ['abduccion-maquina','Abducción en máquina','Glúteos','abduccion','Máquina'],
    ['aduccion-maquina','Aducción en máquina','Aductores','aduccion','Máquina'],
    ['aperturas-crossover','Aperturas de pecho en cable crossover','Pecho','apertura','Polea'],
    ['aperturas-maquina','Aperturas de pecho en máquina','Pecho','apertura','Máquina'],
    ['curl-femoral-acostado','Curl femoral acostado','Isquios','flexion-rodilla','Máquina'],
    ['curl-biceps-z','Curl de bíceps con barra Z','Bíceps','curl','Barra Z'],
    ['curl-biceps-mancuernas','Curl de bíceps con mancuernas','Bíceps','curl','Mancuernas'],
    ['curl-biceps-arnold','Curl de bíceps con una mancuerna a lo Arnold','Bíceps','curl','Mancuerna','Confirmar la variante con el video; el nombre no identifica un único movimiento.'],
    ['curl-biceps-inclinado','Curl de bíceps en banco inclinado','Bíceps','curl','Mancuernas y banco'],
    ['curl-biceps-predicador-maquina','Curl de bíceps en máquina predicador','Bíceps','curl','Máquina'],
    ['curl-biceps-polea','Curl de bíceps en polea baja','Bíceps','curl','Polea'],
    ['curl-biceps-predicador-libre','Curl de bíceps en predicador con peso libre','Bíceps','curl','Banco y peso libre'],
    ['curl-femoral-pie','Curl femoral de pie','Isquios','flexion-rodilla','Máquina'],
    ['curl-femoral-sentado','Curl femoral sentado','Isquios','flexion-rodilla','Máquina'],
    ['dominadas','Dominadas','Espalda','tiron-vertical','Barra de dominadas'],
    ['talones-mancuerna','Elevación de talones de pie con mancuerna','Pantorrillas','pantorrilla','Mancuerna'],
    ['lateral-polea','Elevación lateral en polea','Hombros','elevacion-lateral','Polea'],
    ['posterior-polea','Elevación posterior en polea baja','Deltoide posterior','deltoide-posterior','Polea'],
    ['talones-maquina','Elevación de talones de pie en máquina','Pantorrillas','pantorrilla','Máquina'],
    ['talones-smith','Elevación de talones de pie en Smith','Pantorrillas','pantorrilla','Smith'],
    ['frontal-mancuernas','Elevación frontal con mancuernas y agarre neutro','Hombros','elevacion-frontal','Mancuernas'],
    ['lateral-mancuernas','Elevación lateral con mancuernas','Hombros','elevacion-lateral','Mancuernas'],
    ['lateral-maquina','Elevación lateral en máquina','Hombros','elevacion-lateral','Máquina'],
    ['posterior-mancuernas','Elevación posterior con mancuernas','Deltoide posterior','deltoide-posterior','Mancuernas'],
    ['hip-thrust-barra','Empuje de cadera con barra','Glúteos','extension-cadera','Barra y banco'],
    ['hip-thrust-maquina','Empuje de cadera en máquina','Glúteos','extension-cadera','Máquina'],
    ['extension-piernas','Extensión de piernas en máquina','Cuádriceps','extension-rodilla','Máquina'],
    ['triceps-alta','Extensión de tríceps en polea alta','Tríceps','triceps','Polea'],
    ['triceps-sobre-cabeza','Extensión de tríceps en polea sobre la cabeza','Tríceps','triceps','Polea'],
    ['lagartijas','Lagartijas','Pecho','empuje-horizontal','Peso corporal'],
    ['lagartijas-cerradas-rodillas','Lagartijas cerradas con rodillas en el suelo','Tríceps','empuje-cerrado','Peso corporal'],
    ['lagartijas-cerradas','Lagartijas cerradas','Tríceps','empuje-cerrado','Peso corporal'],
    ['lagartijas-cerradas-rodillas-pausa','Lagartijas cerradas con rodillas en el suelo y pausa abajo','Tríceps','empuje-cerrado','Peso corporal'],
    ['lagartijas-rodillas','Lagartijas con rodillas en el suelo','Pecho','empuje-horizontal','Peso corporal'],
    ['lagartijas-rodillas-pausa','Lagartijas con rodillas en el suelo y pausa abajo','Pecho','empuje-horizontal','Peso corporal'],
    ['patada-lateral-polea','Patada lateral para glúteos en polea','Glúteos','abduccion','Polea y tobillera'],
    ['patada-lateral-tobillera','Patada lateral para glúteos con tobillera','Glúteos','abduccion','Por confirmar','Confirmar si la tobillera tiene peso o está conectada a una resistencia.'],
    ['patada-atras-polea','Patada hacia atrás para glúteos en polea','Glúteos','extension-cadera-aislada','Polea y tobillera'],
    ['patada-atras-tobillera','Patada hacia atrás para glúteos con tobillera','Glúteos','extension-cadera-aislada','Por confirmar','Confirmar si la tobillera tiene peso o está conectada a una resistencia.'],
    ['rumano-barra','Peso muerto semirrígido con barra','Isquios y glúteos','bisagra','Barra'],
    ['rumano-mancuernas','Peso muerto semirrígido con mancuernas','Isquios y glúteos','bisagra','Mancuernas'],
    ['sumo-barra','Peso muerto sumo con barra','Piernas y glúteos','peso-muerto-suelo','Barra'],
    ['jalon-pecho','Polea al pecho','Espalda','tiron-vertical','Polea'],
    ['jalon-cerrado','Polea al pecho con agarre cerrado','Espalda','tiron-vertical','Polea'],
    ['jalon-neutro','Polea al pecho con agarre neutro','Espalda','tiron-vertical','Polea'],
    ['prensa','Prensa de piernas','Cuádriceps y glúteos','sentadilla','Máquina'],
    ['press-hombros-mancuernas','Press de hombros con mancuernas','Hombros','empuje-vertical','Mancuernas'],
    ['press-hombros-maquina','Press de hombros en máquina','Hombros','empuje-vertical','Máquina'],
    ['press-frances','Press francés con mancuernas','Tríceps','triceps','Mancuernas'],
    ['press-inclinado-barra','Press inclinado con barra','Pecho','empuje-inclinado','Barra y banco'],
    ['press-inclinado-mancuernas','Press inclinado con mancuernas','Pecho','empuje-inclinado','Mancuernas y banco'],
    ['press-inclinado-maquina','Press inclinado en máquina','Pecho','empuje-inclinado','Máquina'],
    ['press-militar','Press militar con barra','Hombros','empuje-vertical','Barra'],
    ['press-plano-barra','Press plano con barra','Pecho','empuje-horizontal','Barra y banco'],
    ['press-plano-mancuernas','Press plano con mancuernas','Pecho','empuje-horizontal','Mancuernas y banco'],
    ['press-plano-maquina','Press plano en máquina','Pecho','empuje-horizontal','Máquina'],
    ['pullover-mancuerna','Pullover en banco plano con mancuerna','Tronco','pullover','Mancuerna y banco'],
    ['pullover-polea','Pullover en polea','Espalda','pullover','Polea'],
    ['remo-unilateral-neutro','Remo a una mano con mancuerna y agarre neutro','Espalda','remo','Mancuerna y banco'],
    ['remo-barra','Remo con barra','Espalda','remo','Barra'],
    ['remo-diagonal','Remo con mancuernas y agarre diagonal por confirmar','Espalda','remo','Mancuernas','El usuario pregunta qué variante existe: confirmar agarre y trayectoria en video.'],
    ['remo-mancuernas-neutro','Remo con mancuernas y agarre neutro','Espalda','remo','Mancuernas'],
    ['remo-polea-neutro','Remo neutro en polea','Espalda','remo','Polea'],
    ['remo-polea-cerrado','Remo neutro en polea con agarre cerrado','Espalda','remo','Polea'],
    ['sentadilla-abierta','Sentadilla abierta con mancuerna','Piernas y glúteos','sentadilla','Mancuerna'],
    ['bulgara-una-mancuerna','Sentadilla búlgara con una mancuerna','Piernas y glúteos','sentadilla-unilateral','Mancuerna y banco'],
    ['bulgara-smith','Sentadilla búlgara en Smith','Piernas y glúteos','sentadilla-unilateral','Smith y banco'],
    ['bulgara-mancuernas','Sentadilla búlgara con mancuernas','Piernas y glúteos','sentadilla-unilateral','Mancuernas y banco'],
    ['sentadilla-barra','Sentadilla con barra','Piernas y glúteos','sentadilla','Barra y rack'],
    ['sentadilla-uno-medio','Sentadilla con mancuerna de una repetición y media','Piernas y glúteos','sentadilla-tecnica','Mancuerna'],
    ['goblet','Sentadilla con mancuerna en el pecho','Cuádriceps y glúteos','sentadilla','Mancuerna'],
    ['goblet-media','Sentadilla con mancuerna en el pecho hasta la mitad','Piernas y glúteos','sentadilla-parcial','Mancuerna'],
    ['goblet-talones','Sentadilla con mancuerna en el pecho y talones elevados','Cuádriceps y glúteos','sentadilla','Mancuerna y apoyo de talones'],
    ['hack','Sentadilla hack','Cuádriceps y glúteos','sentadilla','Máquina'],
    ['sentadilla-sumo-baja','Sentadilla sumo con mancuerna abajo','Piernas y glúteos','por-confirmar','Mancuerna','Confirmar si el video muestra sentadilla o peso muerto; no asignar por el nombre.'],
    ['step-up-mancuerna','Step up con mancuerna para glúteos','Piernas y glúteos','step-up','Mancuerna y cajón'],
    ['step-up-smith','Step up en Smith para glúteos','Piernas y glúteos','step-up','Smith y cajón']
  ];
  window.RutaExerciseLibrary = rows.map(([id,name,area,pattern,equipment,note]) => ({ id,name,area,pattern,equipment,note:note || '',status:note ? 'confirmar' : 'disponible',libraryId:'',videoId:'' }));
})();
